---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.extensions.gardener.cloud
spec:
  group: extensions.gardener.cloud
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Cluster
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extensions.extensions.gardener.cloud
spec:
  group: extensions.gardener.cloud
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    plural: extensions
    singular: extension
    kind: Extension
    shortNames:
    - ext
  additionalPrinterColumns:
  - name: Type
    type: string
    description: The type of the Extension resource.
    JSONPath: .spec.type
  - name: State
    type: string
    JSONPath: .status.lastOperation.state
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            type:
              description: Type contains the instance of the resource's kind.
              type: string
            providerConfig:
              description: ProviderConfig holds the configuration for the acting extension controller.
              type: object
          required:
          - type
        status:
          properties:
            lastError:
              description: LastError holds information about the last occurred error
                during an operation.
              properties:
                codes:
                  description: Well-defined error codes of the last error(s).
                  items:
                    type: string
                  type: array
                description:
                  description: A human readable message indicating details about the
                    last error.
                  type: string
              required:
              - description
              type: object
            lastOperation:
              description: LastOperation holds information about the last operation
                on the resource.
              properties:
                description:
                  description: A human readable message indicating details about the
                    last operation.
                  type: string
                lastUpdateTime:
                  description: Last time the operation state transitioned from one
                    to another.
                  format: date-time
                  type: string
                progress:
                  description: The progress in percentage (0-100) of the last operation.
                  format: int64
                  type: integer
                state:
                  description: Status of the last operation, one of Aborted, Processing,
                    Succeeded, Error, Failed.
                  type: string
                type:
                  description: Type of the last operation, one of Create, Reconcile,
                    Delete.
                  type: string
              required:
              - description
              - lastUpdateTime
              - progress
              - state
              - type
              type: object
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this resource.
              format: int64
              type: integer
            state:
              description: State can be filled by the operating controller with what
                ever data it needs.
              type: object
            providerStatus:
              description: Provider-specific output for this control plane
              type: object
          type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsentries.dns.gardener.cloud
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.dnsName
    description: DNS ObjectName
    name: DNS
    type: string
  - JSONPath: .status.providerType
    description: Provider type
    name: TYPE
    type: string
  - JSONPath: .status.provider
    description: Provider
    name: PROVIDER
    type: string
  - JSONPath: .status.state
    description: Status of DNS entry in cloud provider
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSEntry
    listKind: DNSEntryList
    plural: dnsentries
    shortNames:
    - dnse
    singular: dnsentry
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsowners.dns.gardener.cloud
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.ownerId
    description: Owner Id
    name: OWNERID
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSOwner
    listKind: DNSOwnerList
    plural: dnsowners
    shortNames:
    - dnso
    singular: dnsowner
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsproviders.dns.gardener.cloud
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    description: Provider type
    name: TYPE
    type: string
  - JSONPath: .status.state
    description: Status of DNS provider
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: dns.gardener.cloud
  names:
    kind: DNSProvider
    listKind: DNSProviderList
    plural: dnsproviders
    shortNames:
    - dnspr
    singular: dnsprovider
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

